# Generated by Django 4.1.2 on 2023-07-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_educationb"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Educationb",
            new_name="Education",
        ),
    ]
