# Generated by Django 4.1.2 on 2023-07-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0003_rename_educationb_education"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_possition", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField()),
                ("address", models.TextField()),
                ("job_description", models.TextField()),
                ("company_name", models.TextField()),
            ],
        ),
    ]
