# Generated by Django 4.1.2 on 2023-07-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0004_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="company_logo",
            field=models.ImageField(default=1, upload_to=""),
            preserve_default=False,
        ),
    ]
