# Generated by Django 4.1.2 on 2023-07-07 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0005_experience_company_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name="skill",
            name="value",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
