# Generated by Django 4.1.2 on 2023-07-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0006_alter_skill_name_alter_skill_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="grade",
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
