# Generated by Django 4.1.2 on 2023-07-07 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0007_alter_education_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="created_on",
            field=models.DateTimeField(default=datetime.date(2023, 7, 7)),
            preserve_default=False,
        ),
    ]
