# Generated by Django 4.1.2 on 2023-07-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0010_skill_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField(max_length=1000)),
            ],
        ),
    ]
