# Generated by Django 4.1.2 on 2023-07-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="posted",
            field=models.DateTimeField(),
        ),
    ]
